// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNz7vdO-dP0Yn5SvuLbpFsZklKsNRLdO8',
    appId: '1:394152828240:web:9228d47373583a5debe055',
    messagingSenderId: '394152828240',
    projectId: 'youthopp-7dd97',
    authDomain: 'youthopp-7dd97.firebaseapp.com',
    storageBucket: 'youthopp-7dd97.appspot.com',
    measurementId: 'G-WSVXDM4HX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzQNRXm_OqCWsg6il3j98TKppjTIIC4fI',
    appId: '1:394152828240:android:0f08beccdc0fc5ccebe055',
    messagingSenderId: '394152828240',
    projectId: 'youthopp-7dd97',
    storageBucket: 'youthopp-7dd97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEED2c5s4p_Ge3PRT5T5a7DES_0r15REY',
    appId: '1:394152828240:ios:a8b6f70bb37a61bbebe055',
    messagingSenderId: '394152828240',
    projectId: 'youthopp-7dd97',
    storageBucket: 'youthopp-7dd97.appspot.com',
    iosClientId: '394152828240-0sbu8da1jg81dmrc5u8fei4n1vqpp8d6.apps.googleusercontent.com',
    iosBundleId: 'com.example.youth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEED2c5s4p_Ge3PRT5T5a7DES_0r15REY',
    appId: '1:394152828240:ios:a8b6f70bb37a61bbebe055',
    messagingSenderId: '394152828240',
    projectId: 'youthopp-7dd97',
    storageBucket: 'youthopp-7dd97.appspot.com',
    iosClientId: '394152828240-0sbu8da1jg81dmrc5u8fei4n1vqpp8d6.apps.googleusercontent.com',
    iosBundleId: 'com.example.youth',
  );
}
